apiVersion: v1             # Definição do Pod
kind: Pod                  # Tipo do objeto
metadata:                  # Metadados do Pod
  name: db-noticias        # Nome do Pod
  labels:                  # Rótulos do Pod
    app: db-noticias
spec:
  containers:              # Definição do container
    - name: db-noticias-container
      image: docker.io/aluracursos/mysql-db:1 
      ports:                                  
        - containerPort: 3306                 
      envFrom:                              # Referencia a ConfigMap
          - configMapRef:                     
              name: db-configmap              