apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-noticias-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: portal-noticias
  template:
    metadata:
      name: portal-noticias
      labels:
        app: portal-noticias
    spec:
      containers:
        - name: portal-noticias-container
          image: docker.io/aluracursos/portal-noticias:1
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: portal-configmap
          livenessProbe:
            httpGet: # verifica se o container está vivo
               path: / # caminho para a verificação de saúde
               port: 80
            periodSeconds: 10  # intervalo entre as verificações
            failureThreshold: 3 # número de falhas antes de considerar o container como não saudável e reiniciá-lo
            initialDelaySeconds: 20 # tempo de espera antes da primeira verificação apos o container iniciar
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"