apiVersion: v1
kind: Pod
metadata:
  name: portal-noticias
  labels:
    app: portal-noticias
spec:
  containers:
    - name: portal-noticias-container
      image: docker.io/aluracursos/portal-noticias:1
      ports:
        - containerPort: 80
      envFrom:                # Referencia a ConfigMap
        - configMapRef:
            name: portal-configmap # Nome do ConfigMap referenciado
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"      
