apiVersion: v1
kind: Pod
metadata:
  name: sistema-noticias
  labels:
    app: sistema-noticias
spec:
  containers:
    - name: sistema-noticias-container
      image: docker.io/aluracursos/sistema-noticias:1
      ports:
        - containerPort: 80
      envFrom:                # Referencia a ConfigMap
        - configMapRef:
            name: sistema-configmap # Nome do ConfigMap referenciado 